[build]
builder = "nixpacks"

[deploy]
startCommand = "node server.js"

[deploy.variables]
DB_HOST     = "${{ Postgres.PGHOST }}"
DB_PORT     = "${{ Postgres.PGPORT }}"
DB_USER     = "${{ Postgres.PGUSER }}"
DB_PASSWORD = "${{ Postgres.PGPASSWORD }}"
DB_NAME     = "${{ Postgres.PGDATABASE }}"
